Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > What exactly the error?
> 
> hardware/libhardware/modules/camera/3_4/camera.cpp:502:9: error: non-constant-expression cannot be narrowed from type 'std::__1::vector<camera3_stream_buffer, std::__1::allocator<camera3_stream_buffer> >::size_type' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
>         request->output_buffers.size(),
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Sahaj: Can you throw the error into the commit message, so the rational gets preserved if this gets merged?

Patch-set: 2
Reviewer: John Stultz <1010110@85c56323-6fa9-3386-8a01-6480fb634889>