Update patch set 1
Patch Set 1: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset creates breakage in AOSP.  The following snippet of `make` output may point you in the right direction:
frameworks/base/services/jni/com_android_server_location_GpsLocationProvider.cpp: In function 'void android::set_capabilities_callback(uint32_t)':
frameworks/base/services/jni/com_android_server_location_GpsLocationProvider.cpp:112:5: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'uint32_t {aka unsigned int}' [-Wformat]
frameworks/base/services/jni/com_android_server_location_GpsLocationProvider.cpp: In function 'void android::android_location_GpsLocationProvider_class_init_native(JNIEnv*, jclass)':
frameworks/base/services/jni/com_android_server_location_GpsLocationProvider.cpp:276:72: error: 'ULP_RAW_CMD_INTERFACE' was not declared in this scope
make: *** [out/target/product/generic/obj/SHARED_LIBRARIES/libandroid_servers_intermediates/com_android_server_location_GpsLocationProvider.o] Error 1



Patchset creates merge conflict in Google's internal tree.

If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 1
Label: Verified=-1